### ISSUE TITLE
2_netwhat/3_subnet_mask 에서 오타가 있는 것 같습니다.

### ISSUE THREAD

**Issue by exgs** [365kim/42_cursus#2]
안녕하세요.  netwhat을 잘 정리해주셔서 도움이 크게 됩니다.
오타를 발견해서 issue에 올립니다.
(--)
255.255.000.000 == 11111111 11111110 00000000 00000000 == /15
(++)
255.25**4**.000.000 == 11111111 11111110 00000000 00000000 == /15

감사합니다.

**Comment by 365kim** [comment]
exgs님 안녕하세요, 
도움이 되셨다니 기쁩니다

예제를 16에서 15로 고치다가 덜고쳐진 모양이네요...
지적해 주신덕분에 올바르게 수정했습니다. 
피드백 주셔서 감사합니다!
