### ISSUE TITLE
ft_printf 부족한 example 케이스

### ISSUE THREAD

**Issue by progresshans** [365kim/42_cursus#3]
*.* 관련 케이스가 없습니다.

**Comment by 365kim** [comment]
hhan님 안녕하세요
말씀해주신 precision 예제는 있는 것으로 확인됩니다
구체적으로 알려주시면 보완에 참고하겠습니다
감사합니다 :)

**Comment by progresshans** [comment]
@365kim 앗 마크다운 문법때문에 사라졌네요!
```
*.*
```
관련 example이 없는것 같아요

**Comment by 365kim** [comment]
네 감사합니다
빠른 시일 내에 보충해놓겠습니당
